theme = "catppuccin_mocha_transparent"

[editor]
line-number = "relative"
mouse = true
middle-click-paste = true
auto-completion = true
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
